### ISSUE TITLE
[Bug]: Auth

### ISSUE THREAD

**Issue by hryhorash** [cjaliaga/home-assistant-aquarea#105]
### The problem

Connection to the cloud stopped working. When i disabled the integration and tried to login via the panasonic website, I encountered the 2fa process, that was not there before.
Probably it is the cause of the problem, but I could not find the option to disable 2fa in the panasonic account.

Then, I tried to reconnect my panasonic account from scratch, and it did not work. 
P.S. I also received a verification code from panasonic via sms

### What version of Home Assistant Core are you running?

core-2024.3.0

### What type of installation are you running?

Home Assistant OS

### What version of the integration are you running?

v0.6.3

### Device description

- 1 zone
- supports cooling
- supports DHW

### Is the integration loading?

Yes

### Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?

Yes

### Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?

Yes

### Anything in the logs?

```txt
Logger: custom_components.aquarea.config_flow
Source: custom_components/aquarea/config_flow.py:144
integration: Aquarea Smart Cloud ([documentation](https://github.com/cjaliaga/home-assistant-aquarea), [issues](https://github.com/cjaliaga/home-assistant-aquarea/issues))
First occurred: 08:19:16 (2 occurrences)
Last logged: 08:20:16

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 246, in login
    await self._login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 266, in _login_production
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 214, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-0999 - Logged out due to system error. Please login again after a while.
```

**Comment by flix4f** [comment]
Same behavior here. Login via browser on the Aquarea does succeed. Albeit with a new comment on the bottom of the page referring to an’update’ 
![IMG_2825](https://github.com/cjaliaga/home-assistant-aquarea/assets/54268400/aece8ae8-a94e-4817-84f9-15911ffe8273)

Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 7:43:41 AM (1 occurrences)
Last logged: 7:43:41 AM

Error setting up entry felixkleisen@xxx.comfor aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 246, in login
    await self._login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 266, in _login_production
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 214, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-0999 - Logged out due to system error. Please login again after a while.

**Comment by mr0711** [comment]
Same problem here. Login at website still works with 2fa but nothing is working in HA.


```
2024-03-18 06:01:30.610 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xx.xxx@mail.com for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 246, in login
    await self._login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 266, in _login_production
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 214, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-0999 - Logged out due to system error. Please login again after a while.
```

![image](https://github.com/cjaliaga/home-assistant-aquarea/assets/104492108/59b69174-1e46-4d03-b3cf-1f93d6607e36)

**Comment by OUEST-DIGIT** [comment]
The same for me

**Comment by sprzednowek** [comment]
same here

`Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 8:11:53 AM (4 occurrences)
Last logged: 8:16:47 AM

Error setting up entry [my email address] for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 214, in login
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 179, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-0999 - Logged out due to system error. Please login again after a while.`

**Comment by sokrates209** [comment]
exactly the same problem :(

**Comment by denisbobovnik** [comment]
same problem here

**Comment by Borova357** [comment]
same problem here

**Comment by xriser** [comment]
There is a new option in the menu "account management"
Here I found "reset mfa", but it doesn't work
<img width="787" alt="Screenshot 2024-03-18 at 10 02 33" src="https://github.com/cjaliaga/home-assistant-aquarea/assets/21225105/81387671-f0c6-495c-9da7-8414da15251c">

**Comment by sokrates209** [comment]
> There is a new option in the menu "account management" Here I found "reset mfa", but it doesn't work <img alt="Screenshot 2024-03-18 at 10 02 33" width="787" src="https://private-user-images.githubusercontent.com/21225105/313594299-81387671-f0c6-495c-9da7-8414da15251c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTAyMTIsIm5iZiI6MTcxMDc0OTkxMiwicGF0aCI6Ii8yMTIyNTEwNS8zMTM1OTQyOTktODEzODc2NzEtZjBjNi00OTVjLTlkYTctODQxNGRhMTUyNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4MTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOWI0NWU0YjYxOTYzZjg2N2RlZjVhMzY3MGI1NzM5MmE2ZDY4YjU1NmU4MTM1ODU4NDVkNDM4ZWZkNzVkZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNtxCyzVCFSGdx9nlKu_IY_Om2Lc64a53-zkPlo63ws">
> 
> UPD: It seems reset doesn't mean remove. I managed to reset mfa, but when I try to login again, it just reask country and phone number. It seems there is a high chance that the integration will no longer work :(

I've use that, but it doesn't disable 2fa, You just have a choice of type of 2fa, ex You can use Your google auth app to do that or email with code, etc

**Comment by FoxMike1** [comment]
Same problem since 9 hours now. After using 2fa on PC with Google Autehnticator I could use the Aquarea app on my Android Pixel without 2fa from the same IP, very strange. But HA from the same IP no connection to Aquarea.

**Comment by tson0n0** [comment]
Same here, they change the authentification method.
Good luck for the dev.

**Comment by xriser** [comment]
> Same problem since 9 hours now. After using 2fa on PC with Google Autehnticator I could use the Aquarea app on my Android Pixel without 2fa from the same IP, very strange. But HA from the same IP no connection to Aquarea.

I can guess they have changed the auth domain
I don't remember there being https://authglb.digital.panasonic.com/login before

**Comment by viliusdidit** [comment]
opened a tkt in aioaquarea project.

web login process to https://authglb.digital.panasonic.com/usernamepassword/login looks like this, don't have a setup for sniff the mobile app atm; Mobile app v1.20.0 (dev 14,2023) seems to be opening pic-in-pic chrome window to call authglb:
```
<client_id>vf2i6hW5hA2BB2BQGfTHXM4YFyW4I06K</client_id>
<redirect_uri>https://aquarea-smart.panasonic.com/authorizationCallback?lang=en</redirect_uri>
<tenant>pdpauthglb-a1</tenant>
<response_type>code</response_type>
<scope>openid offline_access</scope>
<audience>https://digital.panasonic.com/vf2i6hW5hA2BB2BQGfTHXM4YFyW4I06K/api/v1/</audience>
<_csrf>9OCkcl4F-fgQCE4wTTDWTMQnIHnO-Ek1wBlk</_csrf>
<state>hKFo2SAweUM4X0tybnhUNmZtSUZVdTlfTFVkdjQwZ0Z4TWJHeKFupWxvZ2luo3RpZNkgOG9rMzZOVkNjemJkRlN2a0J1YkN3OHdyczZ3S2RJTmOjY2lk2SB2ZjJpNmhXNWhBMkJCMkJRR2ZUSFhNNFlGeVc0STA2Sxx</state>
<_intstate>deprecated</_intstate>
<username>Panasonic@xxx</username>
<password>xxxx</password>
<lang>en</lang>
<connection>PanasonicID-Authentication</connection>
```

**Comment by vukisz** [comment]
Yes same as for everyone. 
I have two panasonic accounts. One main and another dedicated to HA. 
Main one does not require to setup up 2 factor authentication when logging in into Panasonic cloud. But it also does not work with Panasonic Comfort Cloud - HomeAssistant Component

**Comment by man010** [comment]
Hello same issue here, I passed under review everything, it looks like an authentication issue, while I manage to authenticate to smart cloud with this account.

**Comment by RedwoodNL** [comment]
Panasonic is rendering the use for multiple accounts useless. Comfort Cloud for aircon's was done earlier this year, expecting this is the Smart Cloud update. From now on just one account for multiple devices. Hopefully this makes things easier for the future.
Roll-out started about 12 hours ago.

**Comment by cjaliaga** [comment]
Hi everyone,

Thanks a lot for reporting the issue. The main investigation will happen on the issue that @viliusdidit created on the aioaquarea repo:
- https://github.com/cjaliaga/aioaquarea/issues/44

**Unfortunately I need to set expectations here: A change like this is not simple, hopefully the new login system will allow us to do things in a better way, but it might also happen that we don't manage to get the integration working again in some time. We'll highly appreciate all your patience and any support that you can provide trying to reverse engineering the new process.** 

I'll update the README.

**Comment by xriser** [comment]
> PS: This is the reason I really need to flash my CZ-TAW and make this not cloud/panasonic dependant xD

Please share any decent projects with the reflashing module.

**Comment by os11k** [comment]
I bit the bullet and ordered a Modbus adapter for my Panasonic just now. I mostly use this integration for power consumption monitoring. For my heat pump control, I was using my own small PHP script, but I'm fed up with fixing it every time Panasonic makes changes.

**Comment by RedwoodNL** [comment]
> I bit the bullet and ordered a Modbus adapter for my Panasonic just now. I mostly use this integration for power consumption monitoring. For my heat pump control, I was using my own small PHP script, but I'm fed up with fixing it every time Panasonic makes changes.

Hopefully this was the last time 😂

**Comment by xriser** [comment]
> I bit the bullet and ordered a Modbus adapter for my Panasonic just now. I mostly use this integration for power consumption monitoring. For my heat pump control, I was using my own small PHP script, but I'm fed up with fixing it every time Panasonic makes changes.

I've searched over the internet and ordered HeishaMon communication PCB
It is fully local and can work in parallel with CZ-TAW.

**Comment by os11k** [comment]
> HeishaMon communication PCB
> It is fully local and can work in parallel

That is an interesting device, but I think to work in parallel, you need an additional board. I personally prefer Modbus because I have experience working with it on my ventilation system. But that price is a steal!

**Comment by Laksepote** [comment]
I have ordered the HeishaMon as well. It seems, you can't control your heatpump from both mqtt and CZ-TAW, but with the optional print, you can monitor from the HeishaMon while controlling from the CZ-TAW. I dont have the optional print though, and I plan to replace the CZ-Taw. Maybe ill sell it on Ebay for twice the amount of the HeishaMon :-D

**Comment by RedwoodNL** [comment]
On the K, L and upcoming M series you can connect north the Heishamon and TAW. There is also a goheishamon custom firmware for the TAW, not sure what it does.
For the H and J you need the extra nsp print, which is quite expensive. 

but can you actually control now with the heishamon? It’s still only monitoring right?

**Comment by Laksepote** [comment]
It seems so: https://www.tindie.com/products/thehognl/heishamon-communication-pcb/

**Comment by lmahave** [comment]
I have sent this to Panasonic.
I used the Caliaga integration in Home Assistant to be able to manage my aquarium from there.
It has stopped working, because they have decided to change the login api, without notice. It seems that they try to avoid those sessions, to force us to handle their application.
Your application still works, but it has nothing to do with the possibilities that homeassistant provides.
Can they even predict what time to start, depending on the solar time, the expected temperature or sunshine, the solar production of the panels, the needs for presence at home...? No, of course they can't.
It seems to me an outrage unworthy of a supposedly great brand. It has happened with some other "big" brand and the response from the hoemassistant community made them change.
Let them know that we will start an information campaign about their actions, so that anyone who intends to properly manage their home automation does not buy Panasonic. It's degrading. They cannot ignore a community in this way and I am sure they will pay dearly in the long or medium term.
I hope they rectify in time.
Greetings

**Comment by cedcabgit** [comment]
Let’s start the buzzz
![IMG_9355](https://github.com/cjaliaga/home-assistant-aquarea/assets/157713095/88482b52-997a-47d8-94e5-7cd0f71cdd2c)

**Comment by lmahave** [comment]
Muchas gracias. Molto gracie.

*Luis Carlos Mahave Riaño*

**Comment by MarkMikkelsen83** [comment]
Follow!!!

**Comment by bimusiek** [comment]
Hey guys, please check my implementation under https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2
It implements new Auth0 login for Panasonic Cloud

**Comment by RedwoodNL** [comment]
> Hey guys, please check my implementation under [Hernas/homebridge-panasonic-heat-pump@dd04fc2](https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2) It implements new Auth0 login for Panasonic Cloud

so wait... you've fixed it?

**Comment by cedcabgit** [comment]
> > Hey guys, please check my implementation under [Hernas/homebridge-panasonic-heat-pump@dd04fc2](https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2) It implements new Auth0 login for Panasonic Cloud
> 
> so wait... you've fixed it?

I Think there’s everything in that code to fix our integration but we have to identify what we have to reuse and at what place in @cjaliaga code to make it work again.

**Comment by cjaliaga** [comment]
> > > Hey guys, please check my implementation under [Hernas/homebridge-panasonic-heat-pump@dd04fc2](https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2) It implements new Auth0 login for Panasonic Cloud
> 
> > 
> 
> > so wait... you've fixed it?
> 
> 
> 
> I Think there’s everything in that code to fix our integration but we have to identify what we have to reuse and at what place in @cjaliaga code to make it work again.

The amazing @bimusiek changes are for his Typescript implemention. I'll apply the same logic to our aioaquarea library (in python) later today and let's see if we can get the integration back working.

**Comment by cedcabgit** [comment]
> > > > Hey guys, please check my implementation under [Hernas/homebridge-panasonic-heat-pump@dd04fc2](https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2) It implements new Auth0 login for Panasonic Cloud
> > 
> > 
> > > 
> > 
> > 
> > > so wait... you've fixed it?
> > 
> > 
> > I Think there’s everything in that code to fix our integration but we have to identify what we have to reuse and at what place in @cjaliaga code to make it work again.
> 
> The amazing @bimusiek changes are for his Typescript implemention. I'll apply the same logic to our aioaquarea library (in python) later today and let's see if we can get the integration back working.

In case it helps, support from GPT:

![IMG_9368](https://github.com/cjaliaga/home-assistant-aquarea/assets/157713095/13c6b146-114c-4031-a8f7-d011c042a638)

![IMG_9369](https://github.com/cjaliaga/home-assistant-aquarea/assets/157713095/687612a2-e01f-443a-b7b6-3e839826b01c)

—

from requests_oauthlib import OAuth2Session

# Replace these with your client's information
client_id = 'YOUR_CLIENT_ID'
client_secret = 'YOUR_CLIENT_SECRET'
authorization_base_url = 'https://provider.com/oauth/authorize'
token_url = 'https://provider.com/oauth/token'

# Redirect user to provider for authorization
oauth = OAuth2Session(client_id)
authorization_url, state = oauth.authorization_url(authorization_base_url)
print('Please go here and authorize:', authorization_url)

# Get the authorization verifier code from the callback URL
redirect_response = input('Paste the full redirect URL here: ')

# Fetch the access token
token = oauth.fetch_token(token_url, client_secret=client_secret,
                          authorization_response=redirect_response)

# Use the access token to make authenticated requests
r = oauth.get('https://provider.com/resource')
print(r.content)

**Comment by aLAN-LDZ** [comment]
> > > > Hey guys, please check my implementation under [Hernas/homebridge-panasonic-heat-pump@dd04fc2](https://github.com/Hernas/homebridge-panasonic-heat-pump/commit/dd04fc2b7a207a2648d7ad94bb8eb19052d21bf2) It implements new Auth0 login for Panasonic Cloud
> > 
> > 
> > > 
> > 
> > 
> > > so wait... you've fixed it?
> > 
> > 
> > I Think there’s everything in that code to fix our integration but we have to identify what we have to reuse and at what place in @cjaliaga code to make it work again.
> 
> The amazing @bimusiek changes are for his Typescript implemention. I'll apply the same logic to our aioaquarea library (in python) later today and let's see if we can get the integration back working.

Hello, do we know yet whether integration can be repaired? I don't know whether to switch to a local one <3

**Comment by cjaliaga** [comment]
@aLAN-LDZ hopefully it'll be repaired. I hope to publish an update soon :)

**Comment by aLAN-LDZ** [comment]
> @aLAN-LDZ hopefully it'll be repaired. I hope to publish an update soon :)

You are the best! :)

**Comment by cjaliaga** [comment]
Great news, thanks to the amazing @bimusiek implementation, I have a working version of the aioaquarea library. There has been some modifications to the library due to the auth breaking changes and I'm sure we will have some unexpected behaviors and edge cases. Plus some required refactor and extra logging that I'm sure will need to be added.

In order to unblock everyone I'm releasing a new version of the integration using the revamped login method but **be aware that we're not bug free as we're missing some testing**. Please report everything that you find!!

**Comment by tkamj** [comment]
Hi. Just updated and everything is back to normal from my perspective after just few minutes of using. Thanks for all your work! I’ll report in case of any issues.

**Comment by cedcabgit** [comment]
Thanks a lot!
Everything back to normal after upgrade.
You’re the best @cjaliaga

**Comment by figaro-smartotum** [comment]
Currently working for me!
Absolutely GREAT, your work is priceless.

For other users: you should first configure the phone number using the standard Panasonic login. After doing this, the integration will start to properly work again, without any kind of modification on HA side.

**Comment by aLAN-LDZ** [comment]
I haven't noticed any problems at the moment. Thanks you are great!

**Comment by Boooomerang** [comment]
It’s working here! Awesome! Will send some free beer your way!

**Comment by aLAN-LDZ** [comment]
> Currently working for me! Absolutely GREAT, your work is priceless.
> 
> For other users: you should first configure the phone number using the standard Panasonic login. After doing this, the integration will start to properly work again, without any kind of modification on HA side.

exactly, it didn't work for me without this step

**Comment by denisbobovnik** [comment]
i got it working for a split second, showing all the data, then became unavailable, and this was in the logs

This error originated from a custom integration.

Logger: custom_components.aquarea.coordinator
Source: helpers/update_coordinator.py:313
Integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 11:01:54 AM (10 occurrences)
Last logged: 11:03:24 AM

Unexpected error fetching aquarea-testableminds@gmail.com-B344347134 data: 'token'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/coordinator.py", line 67, in _async_update_data
    await self.device.refresh_data()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 921, in refresh_data
    self._status = await self._client.get_device_status(self._info.long_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 70, in _wrap
    response = await fn(client, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 481, in get_device_status
    response = await self.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 223, in request
    self._access_token = data["accessToken"]["token"]
                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'token'

**Comment by RedwoodNL** [comment]
Working like a charm here. Good job! Epic.

add a (https://www.buymeacoffee.com/) link! You deserve it.

**Comment by os11k** [comment]
> i got it working for a split second, showing all the data, then became unavailable, and this was in the logs
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.aquarea.coordinator Source: helpers/update_coordinator.py:313 Integration: Aquarea Smart Cloud (documentation, issues) First occurred: 11:01:54 AM (10 occurrences) Last logged: 11:03:24 AM
> 
> Unexpected error fetching aquarea-testableminds@gmail.com-B344347134 data: 'token' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh self.data = await self._async_update_data() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/aquarea/coordinator.py", line 67, in _async_update_data await self.device.refresh_data() File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 921, in refresh_data self._status = await self._client.get_device_status(self._info.long_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 70, in _wrap response = await fn(client, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 481, in get_device_status response = await self.request( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 223, in request self._access_token = data["accessToken"]["token"] ~~~~~~~~~~~~~~~~~~~^^^^^^^^^ KeyError: 'token'

I'm getting same error. I did try meanwhile Comfort cloud app, maybe after you try Comfort cloud app integration stops to work? Because I was surprised that Comfort cloud was not logging me out with working home assistant integration. Before 18th march it was constantly logging me out in comfort cloud app.

**Comment by Maison-GIDON** [comment]
> Great news, thanks to the amazing @bimusiek implementation, I have a working version of the aioaquarea library. There has been some modifications to the library due to the auth breaking changes and I'm sure we will have some unexpected behaviors and edge cases. Plus some required refactor and extra logging that I'm sure will need to be added.
> 
> In order to unblock everyone I'm releasing a new version of the integration using the revamped login method but **be aware that we're not bug free as we're missing some testing**. Please report everything that you find!!

you are the best !!!! thank you very much <3

**Comment by denisbobovnik** [comment]
> integration

No, mine isn't logging out too. But i have separate account for HA integrstion shared by my main account which i also use to login to panasonic cloud

**Comment by lmahave** [comment]
It works well. I had to delete the added user and add it again, the way Carlos says in the documentation. What's more, I have not used another email; just an alias. v.g.: main user: juanayuso@gmail.com; alias: juan.ayuso@gmail.com.
Thank you very much, Carlos.

**Comment by robbo1001** [comment]
Working brilliantly here. A big thanks for all the hard work!

**Comment by stephanlarsson** [comment]
Great job! Thank you so much for the fix!!!! ❤️

**Comment by man010** [comment]
Thanks so much Carlos for your efforts to have this integration working again. I confirm it seems to be working flawlessly since this morning.

**Comment by cjaliaga** [comment]
Hi,

We've found an issue when the token expires and its refresh process that lets the integration in a state where is not able to retrieve the data until it's reloaded. You'll find the entities as "unavailable". This would probably happen once every 24H, correlating with token expiration. I'll try to release a hotfix at the earliest, for the time being please reload the integration.

Thanks!

**Comment by rcarvajales** [comment]
Hi, 
Thanks for the fix, the login itself now works for me! however, I can no longer see the climate entity, only the water heater and the exterior temperature. But I lost the hability of changing climate parameters, am I the only one?

![image](https://github.com/cjaliaga/home-assistant-aquarea/assets/57574368/b8a277b6-5783-4e20-bfd6-a81cf66c2046)

**Comment by rcarvajales** [comment]
> Hi, Thanks for the fix, the login itself now works for me! however, I can no longer see the climate entity, only the water heater and the exterior temperature. But I lost the hability of changing climate parameters, am I the only one?

Ok, in case someone find the same issue, please double check your HA Core version is 2024.02 or latest as stated in the Readme.md.
My climate entity is working again.
Thanks a lot!

**Comment by arnolds77** [comment]
Thank you cjaliaga. Great job!!!

**Comment by denisbobovnik** [comment]
that fixed it for me yes!! does anyone know how can i get the full spectre from -5 to 5 settings of my heat pump to homekit? it only shows from 0 to 5.

**Comment by rivojo** [comment]
Let's show our support for the Carlos! 
Every contribution helps keep his great work going.
https://buymeacoffee.com/cjaliaga

**Comment by mirddin** [comment]
Seems like they changed smth again today, integration stopped working and MFA is enforced.

**Comment by Ki3l0n** [comment]
I had the same issue, integration stopped working this morning due to 2FA

**Comment by dabekp** [comment]
Yesterday I lost the connection with the pump so I did a reset according to the manufacturer's recommendations (I held the reset button for 10 seconds). After doing this, communication with the manufacturer's software returned but I lost the connection with my Home Assistant. The difference I noticed is that logging in to the application now takes place in two stages. First, you have to enter the login and password, which are the previous ones, and then a code is sent to the phone number. When trying to connect to HA, an authorization error 1001-1401 pops up. Please, can someone help me with this situation? I will add that I did not work hard to operate the pump with HA and so far it worked great, definitely better than with the original application.

**Comment by dabekp** [comment]
Is there still a chance for this integration to work?

**Comment by devboyz089** [comment]
i'm interested in that too!

**Comment by lrodorigo-apo** [comment]
Control web page is not accessible anymore.
We are now forced to download and use an app.

Is it possible to test the login procedure on
https://accountglb.digital.panasonic.com/

Someone want to cooperate to try to fix this error?
Please help each other to restore this wonderful integration !

The login on HA is failing with the following log.

```
2025-05-08 12:09:19.736 ERROR (MainThread) [custom_components.aquarea.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by tardnuk** [comment]
Is this still not resolved? I am getting same error.

**Comment by devboyz089** [comment]
I managed to get it working via the secondary account approach mentioned somewhere here. It should work.

**Comment by suprimex** [comment]
> Is this still not resolved? I am getting same error.

I have been using successfully this fork for a long time now: https://github.com/wpatrik14/aioaquarea

**Comment by denisbobovnik** [comment]
> I managed to get it working via the secondary account approach mentioned somewhere here. It should work.

@devboyz089 care to point me to where you saw that? i've been waiting for any progress on this integration since last year and still none, yet i've not yet decided to try the heishamon mod, since i dont want to break anything.

**Comment by tardnuk** [comment]
@devboyz089 @denisbobovnik I saw this tip somewhere, probably in different issue, but I am stuck on sharing the device to different account (e-mail), if I got it correctly. Or is it some secondary sub-user that I need to add while adding CZ-TAW1B?

**Comment by denisbobovnik** [comment]
@tardnuk ok i will try re-adding the CZ-TAW1B to panasonic cloud, to see if i need to input additional users there, i've never done that since first registering back when the authentication was still not 2fa

**Comment by denisbobovnik** [comment]
@tardnuk @devboyz089 nope still gettting an unexpected error when re-adding the integration, now its this in the logs
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

I did notice though, Panasonic has added an Amazon Alexa integration link inside their app, could i possibly get the heat pump, if linked to amazon (i dont have alexa speakers or anything in that ecosystem btw) account, then linking that somehow to home assistant?

**Comment by devboyz089** [comment]
I will check what i have done to make it work (probably this evening i will have the time)

**Comment by flix4f** [comment]
> I will check what i have done to make it work (probably this evening i will have the time)

I get the same error trying to login with the second user account.
@denisbobovnik Adding the Alexa Skill only shows my Air to Heat pump. not the Aquarea AIO

**Comment by dabekp** [comment]
I'm having problem with connecting
Authentication error: Authentication error: API_ERROR - Error in get_acc_client_id: Unexpected status code 401

**Comment by AlbertoBartolomeET** [comment]
> I'm having problem with connecting Authentication error: Authentication error: API_ERROR - Error in get_acc_client_id: Unexpected status code 401

Try to log in with that user first in the mobile App, I remember something about some new T&Cs need to be accepted in the App... 🤞

**Comment by dabekp** [comment]
I tried, but it didn't help. The mobile app connects without any problems. The problem started in HA the day before yesterday.

**Comment by JungDev** [comment]
I have this error from a very long time

Registratore: homeassistant.config_entries
Fonte: config_entries.py:761
Prima occorrenza: 29 novembre 2025 alle ore 09:14:33 (3 occorrenze)
Ultimo accesso: 10:02:17

Error setting up entry censured@mail.eu for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by dabekp** [comment]
The app started working. I re-downloaded the files and it turned out to be the newer version, 1.30, when I had 1.29. HA didn't indicate an update. Thanks for the help.

**Comment by lczarnec693** [comment]
Hi,

I’m having an issue with logging in to Panasonic Comfort Cloud via patrik14 custom integration.
The integration worked fine for many months without any changes on my side

Recently login stopped working – entering email and password always fails (unknown error)

Official Panasonic Comfort Cloud mobile app still works (tested via LTE).
Home Assistant login via this integration does not work at all.

My setup:

Panasonic Aquarea model: KIT-ADC7JE5-SM (7 kW, J-generation, split AIO).
Home Assistant: latest stable.
Integration: this repository (aioaquarea / fork by Patrik14). v1.0.30

Could you please advise if this is a known issue or if there is any workaround or fix planned?
