### ISSUE TITLE
two-factor authentication

### ISSUE THREAD

**Issue by ultimo678** [cjaliaga/home-assistant-aquarea#121]
I updated HA and strangely after the update the integration lost the connection to the panasonic cloud. 
I entered the credentials as usual but strangely the procedure didn't work.
Connected through the aquarea-smart.panasonic.com website and I see that it now asks for two-factor authentication to log in. Could this be why I can't connect with the integration? How can I solve it?
Thanks in advance.

**Comment by SP2FET** [comment]
I also noticed this issue, but I was not updating anything - unable to login via integration, but able to login via webpage with 2FA. 
Here's log output from HA:

```
2024-11-06 09:23:02.698 ERROR (MainThread) [custom_components.aquarea.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
await self._api.login()
File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
await self.__login_production()
File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
csrf = response.cookies.get("_csrf").value
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by vukisz** [comment]
Same for started happening for "Panasonic Comfort Cloud" AC integration: https://github.com/sockless-coding/panasonic_cc/issues/331
Most interesting is post of owner with a panasonic changes: https://github.com/sockless-coding/panasonic_cc/issues/331#issuecomment-2458776248
Probably this issue comes from supporting library: https://github.com/cjaliaga/home-assistant-aquarea

**Comment by sokrates209** [comment]
Same here. Just stop working and app is asking for 2FA each time I log in.
![image](https://github.com/user-attachments/assets/e0f903ba-ca14-4f6b-b3d6-69ac9b9137c4)
![image](https://github.com/user-attachments/assets/2db27a39-52dc-49fc-8bfb-e20a082e754d)

**Comment by develvic** [comment]
Similar on my side:
`2024-11-06 10:59:48.446 ERROR (MainThread) [custom_components.aquarea.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-11-06 11:00:04.939 ERROR (MainThread) [custom_components.aquarea.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'`

**Comment by Szakiati** [comment]
Same issue :(

**Comment by amaretto4u** [comment]
same here

This error originated from a custom integration.

Logger: custom_components.aquarea.config_flow
Source: custom_components/aquarea/config_flow.py:144
integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 11:27:57 (1 occurrences)
Last logged: 11:27:57

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by mirddin** [comment]
another vendor "improvement" :(

**Comment by dberschneider** [comment]
Same here. While the login to the Smart Cloud is wonky and barely working, Service Cloud is fortunately still working.

**Comment by Andkago** [comment]
1 up

**Comment by agnarvold** [comment]
> Same here. While the login to the Smart Cloud is wonky and barely working, Service Cloud is fortunately still working.

Are you using "service cloud" with a heatpump-system? I have successfully created a service cloud account myself, but I have an installer watching my system, and I am not able to add my system on service cloud (I suppose it is only possible with 1 service cloud account watching/controlling a system..?). I was in contact with panasonic and they said service cloud is for installers only and not end-user.

**Comment by dberschneider** [comment]
> Are you using "service cloud" with a heatpump-system? I have successfully created a service cloud account myself, but I have an installer watching my system, and I am not able to add my system on service cloud (I suppose it is only possible with 1 service cloud account watching/controlling a system..?). I was in contact with panasonic and they said service cloud is for installers only and not end-user.

I don't have an active installer and registered myself as an installer.

**Comment by Poziomkowy** [comment]
I don't know what happened, but integration is working properly again.

**Comment by develvic** [comment]
Still, not working on my side

**Comment by vukisz** [comment]
Yep started working for me also. 
panasonic_cc (air conditioning) still does not work

**Comment by sokrates209** [comment]
Confirmed, started working for heat pump after HA restart

**Comment by develvic** [comment]
finally, revived after HA restart and re-login

**Comment by cjaliaga** [comment]
Hello everyone, thanks for reporting it! It looks again a temporary outage from the auth system that has been resolved 🥲.

**Comment by fatmacheto** [comment]
Maybe this is related but since this morning I start receiving hundreds of emails that I login to the Panasonic accounts ….



![IMG_5438](https://github.com/user-attachments/assets/8e6c621f-df05-4601-92a4-2329bd69b894)
![IMG_5439](https://github.com/user-attachments/assets/e4ece3f8-02b5-457e-af78-7a60be13403c)

**Comment by amaretto4u** [comment]
Confirm. Working normally again.

**Comment by viliusdidit** [comment]
can also confirm it stared working again. did receive 300 emails this morning, made a mistake by setting up 2fa.
looks like Panasonic backtracked the 2fa/blocking. was able to login using just email/password in incognito browser.

btw, started looking into apple/google login which might be a long term solution to have as a fallback. Anyone familiar enough to hell out implement these? maybe separate thread is better for this subj.

**Comment by dabekp** [comment]
Niestety u mnie po restarcie (przytrzymanie przycisku reset na cz-taw1 przez 10sekund) przestało działać. Usunołem integrację z HA  aby ponownie zainstalować i już się nie da. Przy próbie instalacji blokuje się na autoryzacji. Czy da się coś z tym zrobić, czy raczej mogę się pożegnać z dostępem z HA?

**Comment by dabekp** [comment]
Rejestrator: custom_components.aquarea.config_flow
Źródło: custom_components/aquarea/config_flow.py:144
integracja: Aquarea Smart Cloud ([dokumentacja](https://github.com/cjaliaga/home-assistant-aquarea), [Problemy](https://github.com/cjaliaga/home-assistant-aquarea/issues))
Pierwsze zdarzenie: 07:44:37 (1 zdarzenia)
Ostatnio zalogowany: 07:44:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
