### ISSUE TITLE
Error when try to change setpoint un hvac 

### ISSUE THREAD

**Issue by D-DGIT** [cjaliaga/home-assistant-aquarea#16]
Hello, with the last versión I have this issue when try to change the temperwture setpoint un hvac mode 

[140508536701952] API error: 1000-0999 - Logged out due to system error. Please login again after a while.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 588, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/aquarea/climate.py", line 196, in async_set_temperature
    await self.coordinator.device.set_temperature(temperature, zone.zone_id)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 598, in set_temperature
    await self._client.post_device_zone_heat_temperature(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 473, in post_device_zone_heat_temperature
    return await self._post_device_zone_temperature(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 504, in _post_device_zone_temperature
    response = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 166, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-0999 - Logged out due to system error. Please login again after a while

With water_heater works properly

**Comment by cjaliaga** [comment]
Hey @D-DGIT, could you please check with v0.1.5?

**Comment by D-DGIT** [comment]
Works perfectly 
Great Job!!! Thank you!!

**Comment by cjaliaga** [comment]
Yay!! Thanks, happy to read that 😄
