### ISSUE TITLE
Failed communication with adaptor. Please make sure it is connected to the network or check again after resetting adaptor

### ISSUE THREAD

**Issue by Jabol86** [cjaliaga/home-assistant-aquarea#27]
Unexpected error fetching aquarea-XXXXX458+XXXXX@gmail.com-BXXXXXXXX data: API error: 1000-1503 - Failed communication with adaptor. Please make sure it is connected to the network or check again after resetting adaptor.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/aquarea/coordinator.py", line 57, in _async_update_data
    self._device = await self._client.get_device(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 352, in get_device
    device_info, await self.get_device_status(device_info.long_id), self
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 287, in get_device_status
    response = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 166, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-1503 - Failed communication with adaptor. Please make sure 
it is connected to the network or check again 
after resetting adaptor.

Error setting up entry aquarea-XXXXX458+XXXXX@gmail.com for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by cjaliaga** [comment]
@Jabol86 that error is coming directly from the Aquarea service indicating your adapter is not connected to the network/Panasonic Service. You may try to do what's specified in the error message Panasonic is providing: resetting the adapter/your device and ensuring is properly connected to the network. 

The device has several led status indicators, indicating if it's connected to the network and if it's connected to the Panasonic service.

If you see the device is connected and the integration still doesn't show the entities as available, you can always try to reload it. But this error is coming directly from Panasonic.

**Comment by Jabol86** [comment]
The problem is that the adapter is connected and works without any problems. I normally manage the pump from a cloud service.
