### ISSUE TITLE
Problem with Integration

### ISSUE THREAD

**Issue by kommis** [cjaliaga/home-assistant-aquarea#28]
Hello,

Since today there is a problem with the Integration. In the App is everthing ok an the Adapter works.

Here can you see the log informations:

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/aquarea/__init__.py:52
Integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 20:07:39 (2 occurrences)
Last logged: 20:08:17

Error setting up entry xx@xx.xx for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
`

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.aquarea.coordinator
Source: custom_components/aquarea/coordinator.py:57
Integration: Aquarea Smart Cloud (documentation, issues)
First occurred: 20:07:32 (1 occurrences)
Last logged: 20:07:32

Unexpected error fetching aquarea-xxxx@xx-B38826xxxx data: API error: 1000-1503 - Failed communication with adaptor. Please make sure it is connected to the network or check again after resetting adaptor.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/aquarea/coordinator.py", line 57, in _async_update_data
    self._device = await self._client.get_device(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 352, in get_device
    device_info, await self.get_device_status(device_info.long_id), self
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 287, in get_device_status
    response = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 166, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-1503 - Failed communication with adaptor. Please make sure 
it is connected to the network or check again 
after resetting adaptor.
`
![Screenshot_20221001-201442_Comfort Cloud](https://user-images.githubusercontent.com/95351671/193422741-52688a41-63a7-4fa8-8993-e60dbc538d8d.jpg)

Thanks fo your help!
Best regards

**Comment by kommis** [comment]
I have found the Problem. The Adapter was not connected to Internet.
