### ISSUE TITLE
Receiving error

### ISSUE THREAD

**Issue by bobkolan** [cjaliaga/home-assistant-aquarea#37]
I have his integration running with two heat pumps and it worked fine. But since this morning it gives an error:

Logger: homeassistant.config_entries
Source: custom_components/aquarea/__init__.py:52
Integration: Aquarea Smart Cloud ([documentation](https://github.com/cjaliaga/home-assistant-aquarea), [issues](https://github.com/cjaliaga/home-assistant-aquarea/issues))
First occurred: 15:26:23 (5 occurrences)
Last logged: 17:32:01
Error setting up entry xxx@xxx.xx for aquarea

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

When logging in directly to the Panasonic Service Cloud everything seems to work.
Any idea what's going on?

**Comment by bobkolan** [comment]
since this morning it suddenly worked again. i haven't made any changes.
probably issue was with the panasonic cloud. 
closing issue now.
