### ISSUE TITLE
Login Error 1000-1503

### ISSUE THREAD

**Issue by Bzdregaa** [cjaliaga/home-assistant-aquarea#45]
Error while trying to connect with Smart Cloud
I've tried HACS installation and manual installation.
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/aquarea/coordinator.py", line 57, in _async_update_data
    self._device = await self._client.get_device(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 352, in get_device
    device_info, await self.get_device_status(device_info.long_id), self
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 287, in get_device_status
    response = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 166, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-1503 - Failed communication with adaptor. Please make sure 
it is connected to the network or check again 
after resetting adaptor.`
I can connect with my Heat Pump via Panasonic Aquarea Smart Cloud site.

**Comment by Alwik** [comment]
Same since yesterday, suddenly stopped working:
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/aquarea/coordinator.py", line 57, in _async_update_data
    self._device = await self._client.get_device(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 352, in get_device
    device_info, await self.get_device_status(device_info.long_id), self
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 287, in get_device_status
    response = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 166, in request
    raise ApiError(error.error_code, error.error_message)
aioaquarea.errors.ApiError: API error: 1000-1503 - Failed communication with adaptor. Please make sure 
it is connected to the network or check again 
after resetting adaptor.

**Comment by Alwik** [comment]
Power cycling the heat pump solved it!
