### ISSUE TITLE
Error connecting 

### ISSUE THREAD

**Issue by asanchezol** [cjaliaga/home-assistant-aquarea#48]
Since a few days ago. Since I intall last version of Home assistance I lost contection to my device. Any help?

here you have the log:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 52, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 201, in login
    response: aiohttp.ClientResponse = await self.request(
                                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioaquarea/core.py", line 154, in request
    resp = await self._sess.request(method, AQUAREA_SERVICE_BASE + url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

![IMG_6902](https://github.com/cjaliaga/home-assistant-aquarea/assets/64548589/6aa4df52-0bc6-493e-b5f4-9402cf45e730)

**Comment by Skydras** [comment]
Have the same issue

**Comment by asanchezol** [comment]
Hi all, 

I manage to solve it. I went to the aerotermia and reset the CZ-TAW1 (communication device) and after the connection was reestablished I restarted HA and all was back to normal.
