### ISSUE TITLE
Error with version v0.1.0

### ISSUE THREAD

**Issue by D-DGIT** [cjaliaga/home-assistant-aquarea#5]
Hello,

I have followed the steps to install and I manage to log in but I get the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aquarea/__init__.py", line 54, in async_setup_entry
    devices = await client.get_devices(include_long_id=True)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 49, in _wrap
    response = await fn(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aioaquarea/core.py", line 248, in get_devices
    SensorMode(zone_record["heatSensor"]),
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'Compensation curve' is not a valid SensorMode

I have:

Home Assistant Core (docker): latest version 
HACS: latest version
Aquarea CZ-TAW1

I integrated @ronhks version (MQTT integration) into my home assistant and was able to control my Aquarea.

**Comment by cjaliaga** [comment]
Thanks @D-DGIT for reporting this. I'll have it fixed in https://github.com/cjaliaga/aioaquarea and publish a new version. I completely forgot to add the compensation curve sensor.

**Comment by cjaliaga** [comment]
@D-DGIT https://github.com/cjaliaga/home-assistant-aquarea/releases/tag/v0.1.1 is published and should resolved the issue. Please let me know if that's not the case.
